site_name: Nextflow for the Life Sciences
repo_url: https://github.com/Sydney-Informatics-Hub/nf4ls-materials
repo_name: Sydney-Informatics-Hub/nf4ls-materials

nav:
  - Instructor guide:
    - Who is your audience?: instructor/audience.md # preamble
    - Training logistics: instructor/logistics.md # schedules
    - Training environment: instructor/environment.md # compute and software
    - Training materials: instructor/materials.md # datasets and exercises

theme:
  name: material
  logo: assets/usyd-logo.png
  features:
    - navigation.footer
    - content.code.copy
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57
