site_name: Nextflow for the Life Sciences Training Materials
repo_url: https://github.com/Sydney-Informatics-Hub/nf4ls-materials
repo_name: Sydney-Informatics-Hub/nf4ls-materials

nav:
  - Home: index.md
  - Instructor guides:
      - Training logistics: instructor/logistics.md
      - Training infrastructure: instructor/environment.md
      - Training materials: instructor/materials.md

theme:
  name: material
  logo: assets/usyd-logo.png
  features:
    - navigation.footer
    - content.code.copy
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57